### ISSUE TITLE
 http://data.neuflow.org/data/cifar10.t7.tgz is invalid

### ISSUE THREAD

**Issue by richardhahahaha** [jhjin/kmeans-learning-torch#1]
http://data.neuflow.org/data/cifar10.t7.tgz is invalid. Where can get it?

**Comment by jhjin** [comment]
Hi, could you try it from AWS ? the following works fine for me.

wget http://torch7.s3-website-us-east-1.amazonaws.com/data/cifar10.t7.tgz

**Comment by richardhahahaha** [comment]
It is right. Thanks
